In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [4]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [5]:
print('e^1 equals : ', torch.exp(torch.FloatTensor([1])))

w = torch.zeros((2, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(w) + b)))
print(hypothesis)
print(hypothesis.shape)

e^1 equals :  tensor([2.7183])
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])


In [7]:
print('1/(1 + e^{-1}) equals : ', torch.sigmoid(torch.FloatTensor([1])))
hypothesis = torch.sigmoid(x_train.matmul(w) + b)
print(hypothesis)
print(hypothesis.shape)
print(y_train)

1/(1 + e^{-1}) equals :  tensor([0.7311])
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
torch.Size([6, 1])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [10]:
# cost function
losses = -(y_train * torch.log(hypothesis) + (1 - y_train) * torch.log(1 - hypothesis))
print(losses)
cost = losses.mean()
print(cost)

F.binary_cross_entropy(hypothesis, y_train)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward0>)
tensor(0.6931, grad_fn=<MeanBackward0>)


tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)

In [12]:
w = torch.zeros((2, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([w, b], lr = 1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1) :
    hypothesis = torch.sigmoid(x_train.matmul(w) + b) 
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0 :
        print('epoch : {:4d}/{} Cost : {:.6f}'.format(epoch, nb_epochs, cost.item()))

epoch :    0/1000 Cost : 0.693147
epoch :  100/1000 Cost : 0.134722
epoch :  200/1000 Cost : 0.080643
epoch :  300/1000 Cost : 0.057900
epoch :  400/1000 Cost : 0.045300
epoch :  500/1000 Cost : 0.037261
epoch :  600/1000 Cost : 0.031672
epoch :  700/1000 Cost : 0.027556
epoch :  800/1000 Cost : 0.024394
epoch :  900/1000 Cost : 0.021888
epoch : 1000/1000 Cost : 0.019852
